import pandas as pd
student_marks=pd.Series([98,10,12,56,65,54,24,78])
print(student_marks)
print("maximum marks",student_marks.max())
print("minimum marks",student_marks.min())
print("average marks",student_marks.mean())
print("total marks",student_marks.sum())
print("\n less than 20")
print(student_marks[student_marks<20])
print(student_marks[student_marks>20])